var quoteList;
var currentQuote="";
var currentAuthor="";


function loadQuotes()
{
	var jStr = JSON.stringify(text);
	quoteList = JSON.parse(jStr);
	console.log("List Loaded");
	nextQuote();

	return 0;
}


function nextQuote()
{
	if (quoteList.quotes.length > 0)
	{
		var quoteNumber = Math.floor(Math.random() * (quoteList.quotes.length))
		currentQuote=quoteList.quotes[quoteNumber].quoteText;
		currentAuthor=quoteList.quotes[quoteNumber].author;			
	}
	else
	{
		currentQuote="Another meaningful quote.";
		currentAuthor="Anonymous";			
	}
  
  document.getElementById('quoted').innerHTML = currentQuote;
  document.getElementById('author').innerHTML = '-'+currentAuthor;
  return 0;
}

function sMediaLink(webSite)
{

  var linkAddress="_blank";
  if (webSite=="reddit")
    {
      linkAddress="http://www.reddit.com/submit?url=" + "https://codepen.io/mattrelph/full/zEKPGv" + "&title=" + currentQuote + "-" + currentAuthor;
    }
  else if (webSite=="twitter")
    {
      linkAddress="https://twitter.com/intent/tweet?text=" + currentQuote + "-" + currentAuthor;
    }
  window.open(linkAddress,"_blank");
  return 0;
}


var text = { "quotes" : [
{ "author":" Unknown " , "quoteText":" Hard work pays off in the future. Laziness pays off now. " },
{ "author":" Unknown " , "quoteText":" 3 out of 4 people make up 75% of the population. " },
{ "author":" Unknown " , "quoteText":" 24 hours in a day, 24 beers in a case. Coincidence? You decide. " },
{ "author":" Mark Twain " , "quoteText":" A banker is a fellow who lends you his umbrella when the sun is shining and wants it back the minute it begins to rain. " },
{ "author":" Doug Larson " , "quoteText":" Accomplishing the impossible means only that the boss will add it to your regular duties. " },
{ "author":" Unknown " , "quoteText":" A chicken is an egg\'s way of making another egg. " },
{ "author":" Unknown " , "quoteText":" A closed mouth gathers no foot. " },
{ "author":" Unknown " , "quoteText":" A conscience is what hurts when all your other parts feel so good. " },
{ "author":" Unknown " , "quoteText":" A day for firm decisions! Or is it? " },
{ "author":" Unknown " , "quoteText":" A device that will cut your fuel bills in half: scissors " },
{ "author":" Unknown " , "quoteText":" A dog is a dog unless he is facing you. Then he is Mr. Dog. " },
{ "author":" George Bernard Shaw " , "quoteText":" A government that robs Peter to pay Paul can always depend on the support of Paul. " },
{ "author":" Unknown " , "quoteText":" Always try to make other people happy, even if you have to leave them alone to do it. " },
{ "author":" Unknown " , "quoteText":" A neat desk is a sign of a cluttered desk drawer. " },
{ "author":" Unknown " , "quoteText":" A neat desk is the sign of a sick mind. " },
{ "author":" Unknown " , "quoteText":" A sentence is something you should never put a preposition at the end of. " },
{ "author":" Unknown " , "quoteText":" A signature always reveals a man\'s character - and sometimes even his name. " },
{ "author":" Unknown " , "quoteText":" A sine curve goes off to infinity, or at least to the end of the blackboard. " },
{ "author":" Spike Milligan. " , "quoteText":" A sure cure for seasickness is to sit under a tree. " },
{ "author":" Unknown " , "quoteText":" All men can fly, but sadly, only in one direction - down. " },
{ "author":" Unknown " , "quoteText":" All my life I wanted to be someone. I guess I should have been more specific. " },
{ "author":" Edward R. Murrow " , "quoteText":" Anyone who isn\'t confused really doesn\'t understand the situation. " },
{ "author":" Unknown " , "quoteText":" Always remember you\'re unique, just like everyone else. " },
{ "author":" Unknown " , "quoteText":" Anything worth taking seriously is worth making fun of. " },
{ "author":" Unknown " , "quoteText":" Artificial intelligence is no match for natural stupidity. " },
{ "author":" Unknown " , "quoteText":" Beauty is only skin deep, but ugly goes right to the bone. " },
{ "author":" Unknown " , "quoteText":" Before you criticize someone, you should walk a mile in their shoes. That way, when you criticize them, you\'re a mile away, and you have their shoes. " },
{ "author":" Unknown " , "quoteText":" Be nice to your kids. They\'ll choose your nursing home. " },
{ "author":" Unknown " , "quoteText":" Boomerangs are coming back, Ski slopes are going downhill, but Exit signs are on the way out. " },
{ "author":" Unknown " , "quoteText":" Breaking the law of gravity isn\'t painful it\'s getting caught that hurts. " },
{ "author":" Unknown " , "quoteText":" Caution: do not look into laser with remaining eye. " },
{ "author":" Unknown " , "quoteText":" Change is inevitable, except from a vending machine. " },
{ "author":" Unknown " , "quoteText":" Democracy is four wolves and a lamb voting on what to have for lunch. " },
{ "author":" Unknown " , "quoteText":" Did you know the word gullible is not in the dictionary? " },
{ "author":" Unknown " , "quoteText":" Diplomacy is the art of saying \'good doggie\' while looking for a bigger stick. " },
{ "author":" Unknown " , "quoteText":" Don\'t personify computers - we don\'t like it. " },
{ "author":" Unknown " , "quoteText":" Don\'t use a big word where a diminutive one will suffice. " },
{ "author":" Unknown " , "quoteText":" Don\'t worry about avoiding temptation - as you grow older, it starts avoiding you. " },
{ "author":" Unknown " , "quoteText":" Don\'t worry about the world ending today, it\'s already tomorrow in Australia. " },
{ "author":" Unknown " , "quoteText":" Eagles may soar, but weasels don\'t get sucked into jet engines. " },
{ "author":" Unknown " , "quoteText":" Entertainment is just talking louder than the audience. " },
{ "author":" Unknown " , "quoteText":" Everyone has a photographic memory, some just don\'t have film. " },
{ "author":" Unknown " , "quoteText":" Everyone is someone else\'s weirdo. " },
{ "author":" Unknown " , "quoteText":" Experience is something you get just after you need it. " },
{ "author":" Unknown " , "quoteText":" Free jazz is so called because no-one would ever buy it. " },
{ "author":" Unknown " , "quoteText":" Frisbeetarianism: The belief that when you die, your soul goes up on the roof and gets stuck. " },
{ "author":" Unknown " , "quoteText":" Give a man a fish and you feed him for a day. Teach a man to fish, and you can sell him some tackle. " },
{ "author":" Unknown " , "quoteText":" Grandma used to say \'Money is not the key to happiness. If you have money you can always have a key made.  " },
{ "author":" Unknown " , "quoteText":" Hangover: The wrath of grapes " },
{ "author":" Unknown " , "quoteText":" Happiness makes up in height what it lacks in length. " },
{ "author":" Unknown " , "quoteText":" As a computer, I find your faith in technology amusing. " },
{ "author":" Unknown " , "quoteText":" Ask me about my vow of silence. " },
{ "author":" Unknown " , "quoteText":" Atheism is a non-prophet organisation. " },
{ "author":" Unknown " , "quoteText":" He who laughs last didn\'t understand the joke. " },
{ "author":" Unknown " , "quoteText":" He\'s supposed to sound like he\'s in pain, he\'s a folk singer. " },
{ "author":" Unknown " , "quoteText":" How do you tell when you run out of invisible ink? " },
{ "author":" Oscar Wilde " , "quoteText":" I am not young enough to know everything. " },
{ "author":" Unknown " , "quoteText":" I didn\'t say it was your fault. I said I was going to blame you. " },
{ "author":" Unknown " , "quoteText":" I refuse to have a battle of wits with an unarmed opponent. " },
{ "author":" Unknown " , "quoteText":" I used to be indecisive, now I\'m not so sure. " },
{ "author":" Unknown " , "quoteText":" I wonder how much deeper the ocean would be without sponges. " },
{ "author":" Unknown " , "quoteText":" If you tell the truth, you don\'t have to remember anything. " },
{ "author":" Unknown " , "quoteText":" If you think nobody cares about you, try missing a couple of mortgage payments. " },
{ "author":" Unknown " , "quoteText":" I\'m feeling argumentative. Please contradict me. " },
{ "author":" Unknown " , "quoteText":" I\'m having a deja vu experience, just like last time. " },
{ "author":" Unknown " , "quoteText":" If it weren\'t for the last minute, nothing would get done. " },
{ "author":" Johnny Carson " , "quoteText":" If life was fair, Elvis would be alive and all the impersonators would be dead. " },
{ "author":" Unknown " , "quoteText":" If one synchronized swimmer drowns, do the rest have to drown too? " },
{ "author":" Unknown " , "quoteText":" If today is the first day of the rest of your life, what was yesterday? " },
{ "author":" Unknown " , "quoteText":" If you ate pasta and antipasta, would you still be hungry? " },
{ "author":" Unknown " , "quoteText":" If you strangle a smurf, what color does it turn? " },
{ "author":" Unknown " , "quoteText":" If you lend someone £20, and never see that person again, it was probably worth it. " },
{ "author":" Unknown " , "quoteText":" If you want someone to catch something, throw it at their nose. " },
{ "author":" Unknown " , "quoteText":" It doesn\'t matter how you get there if you don\'t know where you\'re going. " },
{ "author":" Voltaire " , "quoteText":" It is dangerous to be right in matters on which the established authorities are wrong. " },
{ "author":" Unknown " , "quoteText":" It\'s a small world, but I\'d hate to have to paint it. " },
{ "author":" Unknown " , "quoteText":" It\'s not the heights that bother me it\'s falling on the bottoms of them. " },
{ "author":" Unknown " , "quoteText":" I\'ve got a mind like a.. a.. what\'s that thing called? " },
{ "author":" Unknown " , "quoteText":" I\'ve had amnesia for as long as I can remember " },
{ "author":" John Lennon " , "quoteText":" Life is what happens to you while you\'re busy making other plans. " },
{ "author":" Susan Ertz " , "quoteText":" Millions yearn for immortality who don\'t know what to do with themselves on a rainy Sunday afternoon. " },
{ "author":" Unknown " , "quoteText":" My favourite scientific theory is that the rings of Saturn are made of lost airline luggage. " },
{ "author":" Unknown " , "quoteText":" My supply of brain cells is finally down to a manageable size. " },
{ "author":" Unknown " , "quoteText":" Never ask a barber if he thinks you need a haircut. " },
{ "author":" Unknown " , "quoteText":" Never attribute to malice what can be adequately explained by stupidity. " },
{ "author":" Unknown " , "quoteText":" Never test the depth of the water with both feet. " },
{ "author":" Stuart Hughes " , "quoteText":" No issue is so small that it can\'t be blown out of proportion. " },
{ "author":" Unknown " , "quoteText":" No one is listening until you make a mistake. " },
{ "author":" Unknown " , "quoteText":" No problem is so big that you can\'t run away from it. " },
{ "author":" Unknown " , "quoteText":" Of course, you may smoke - but please don\'t exhale. " },
{ "author":" Unknown " , "quoteText":" On the other hand, I have some fingers. " },
{ "author":" Unknown " , "quoteText":" Personifiers of the world! Unite! You have nothing to lose but Mr. Dignity! " },
{ "author":" Unknown " , "quoteText":" Pound for pound, the amoeba is the most vicious animal on earth. " },
{ "author":" Unknown " , "quoteText":" Rome wasn\'t built in a day, it just looks like that. " },
{ "author":" Unknown " , "quoteText":" Smash forehead on keyboard to continue. " },
{ "author":" Unknown " , "quoteText":" Some days you are the fly, other days you are the windscreen. " },
{ "author":" Unknown " , "quoteText":" That\'s OK. I don\'t remember my name either. " },
{ "author":" Unknown " , "quoteText":" The amount of sleep needed by the average person is ten minutes more. " },
{ "author":" Unknown " , "quoteText":" The early bird gets the worm, but the early worm gets eaten. " },
{ "author":" Unknown " , "quoteText":" The face of a child can say it all, especially the mouth part of the face. " },
{ "author":" Woody Allen " , "quoteText":" The lion and the calf shall lie down together but the calf won\'t get much sleep. " },
{ "author":" Damon Runyon " , "quoteText":" The race is not always to the swift, nor the battle to the strong - but that\'s the way to bet. " },
{ "author":" Franklin P. Jones " , "quoteText":" The trouble with being punctual is that nobody\'s there to appreciate it. " },
{ "author":" Indira Gandhi " , "quoteText":" There are two kinds of people, those who do the work and those who take the credit. Try to be in the first group; there is less competition there. " },
{ "author":" Unknown " , "quoteText":" There are three kinds of people - those who can count, and those who can\'t. " },
{ "author":" Unknown " , "quoteText":" There\'s no future in time travel. " },
{ "author":" Unknown " , "quoteText":" Time flies like an arrow, fruit flies like a banana. " },
{ "author":" Unknown " , "quoteText":" To steal ideas from one person is plagiarism; to steal from many is research. " },
{ "author":" Unknown " , "quoteText":" \'Veni, Vidi, Velcro\' -  I came, I saw, I stuck around. " },
{ "author":" Unknown " , "quoteText":" \'Veni, Vidi, Visa\'. I came. I Saw. I did a little shopping. " },
{ "author":" Unknown " , "quoteText":" What sets us apart from animals is that we\'re not afraid of vacuum cleaners. " },
{ "author":" George Bernard Shaw " , "quoteText":" When a stupid man is doing something he is ashamed of, he always declares that it is his duty. " },
{ "author":" Unknown " , "quoteText":" You don\'t need an engine to go downhill. " },
{ "author":" Unknown " , "quoteText":" It\'s important to have an open mind, but not so open that your brains fall out. " },
{ "author":" Unknown " , "quoteText":" The DOPELER Effect is the tendency of stupid ideas to seem smarter when they come at you rapidly " },
{ "author":" Unknown " , "quoteText":" 25% of the general population believe in statistics. The other 80% don\'t trust them at all. " },
{ "author":" Unknown " , "quoteText":" 95% of statistics are just made up anyway. " },
{ "author":" Unknown " , "quoteText":" A new study shows that licking the sweat off a frog can cure depression. The down side is, the minute you stop licking, the frog gets depressed again. " },
{ "author":" Unknown " , "quoteText":" Anything not nailed down is mine. Anything I can pry loose is not nailed down. " },
{ "author":" Unknown " , "quoteText":" I always win. Except when I lose, but then I just don\'t count it. " },
{ "author":" Unknown " , "quoteText":" I went to a restaurant that was so expensive that they didn\'t have prices on the menu - just little faces with varying expressions of horror. " },
{ "author":" Unknown " , "quoteText":" The person who knows how to laugh at himself will never cease to be amused " },
{ "author":" Unknown " , "quoteText":" Where in the nursery rhyme does it say Humpty Dumpty is an egg? " },
{ "author":" Unknown " , "quoteText":" It is impossible to make anything foolproof because fools are so ingenious.  " },
{ "author":" Unknown " , "quoteText":" The trouble with doing something right the first time, is nobody appreciates how difficult it was. " },
{ "author":" Unknown " , "quoteText":" Everybody lies, but it doesn\'t matter since nobody listens. " },
{ "author":" Unknown " , "quoteText":" When I was born, I was so surprised, I couldn\'t talk for a year and a half! " },
{ "author":" Unknown " , "quoteText":" To err is human, to blame the next guy even more so.  " },
{ "author":" Unknown " , "quoteText":" There are two rules for success... 1) Never tell everything you know.  " },
{ "author":" Unknown " , "quoteText":" Be nice to other people; they outnumber you 5.5 billion to one.  " },
{ "author":" Earl Wilson " , "quoteText":" Courage is the art of being the only one that knows you\'re scared to death. " },
{ "author":" Will Rogers " , "quoteText":" Even if you\'re on the right track, you\'ll get run over if you just sit there. " },
{ "author":" G.H. Hill " , "quoteText":" I have given up anarchy. Too many rules - hating the government and all that stuff. " },
{ "author":" Unknown " , "quoteText":" The only reason some people get lost in thought because it is unfamiliar territory. " },
{ "author":" Unknown " , "quoteText":" Talk is cheap because supply exceeds demand. " },
{ "author":" Unknown " , "quoteText":" Start every day off with a smile and get it over with.  " },
{ "author":" Unknown " , "quoteText":" Just because something doesn\'t do what you planned it to do doesn\'t mean it\'s useless. " },
{ "author":" Unknown " , "quoteText":" There are two kinds of people, those who finish what they start and so on.  " },
{ "author":" H. L. Mencken " , "quoteText":" It is the dull man who is always sure, and the sure man who is always dull. " },
{ "author":" William James " , "quoteText":" A great many people think they are thinking when they are merely rearranging their prejudices. " },
{ "author":" Unknown " , "quoteText":" Half of the people in the world are below average.  " },
{ "author":" Unknown " , "quoteText":" Male zebras have white stripes, female zebras have black stripes. " },
{ "author":" Unknown " , "quoteText":" Computers are useless. They can only give answers. " },
{ "author":" Unknown " , "quoteText":" There has been an alarming increase in the number of things you know absolutely nothing about. " },
{ "author":" Quentin Crisp " , "quoteText":" Never keep up with the Joneses. Drag them down to your level. It\'s cheaper. " },
{ "author":" Edward Tufte " , "quoteText":" There are only two industries that refer to their customers as \'users\'. " },
{ "author":" August Strindberg " , "quoteText":" I loathe people who keep dogs. They are cowards who haven\'t got the guts to bite people themselves. " },
{ "author":" Unknown " , "quoteText":" Even if you win the rat race, you\'re still a rat.  " },
{ "author":" Unknown " , "quoteText":" For every problem there is a solution which is simple, neat and wrong.  " },
{ "author":" Unknown " , "quoteText":" Natives who beat drums to drive off evil spirits are objects of scorn to smart people who blow horns to break up traffic jams. " },
{ "author":" Unknown " , "quoteText":" All sweeping generalisations are wrong. " },
{ "author":" Unknown " , "quoteText":" I avoid clichés like the plague. " },
{ "author":" Unknown " , "quoteText":" My sources are unreliable, but their information is fascinating. " },
{ "author":" Andre Gide " , "quoteText":" Believe those who seek the truth; doubt those that find it. " },
{ "author":" Unknown " , "quoteText":" When you find yourself in a hole, the first thing to do is stop digging. " },
{ "author":" Unknown " , "quoteText":" Democracy is the worst possible form of government, except for all the others. " },
{ "author":" Unknown " , "quoteText":" We have the finest politicians that money can buy. " },
{ "author":" Unknown " , "quoteText":" Never explain -- your Friends do not need it and your enemies will not believe you anyway. " },
{ "author":" Unknown " , "quoteText":" If it\'s stupid but works, it isn\'t stupid. " },
{ "author":" Albert Einstein " , "quoteText":" It is a miracle that curiosity survives formal education. " },
{ "author":" Sgt Phil Girvan " , "quoteText":" I used to know everything, till everything changed. " },
{ "author":" Unknown " , "quoteText":" You can have peace, or you can have freedom. Don\'t ever count on having both at once. " },
{ "author":" Unknown " , "quoteText":" Anything free is worth the price. " },
{ "author":" Unknown " , "quoteText":" Always listen to experts. They\'ll tell you what can\'t be done, and why. Then go and do it anyway. " },
{ "author":" Edmund Burke " , "quoteText":" All that is necessary for the forces of evil to take root in the world is for enough good men to do nothing. " },
{ "author":" Groucho Marx " , "quoteText":" I find television very educational. Every time someone switches it on I go into another room and read a good book. " },
{ "author":" Unknown " , "quoteText":" Wisdom has two parts: 1) Having a lot to say, and 2) not saying it. " },
{ "author":" Unknown " , "quoteText":" I\'m not stupid. I just have a command of thoroughly useless information. " },
{ "author":" Unknown " , "quoteText":" People will accept your ideas much more readily if you tell them Benjamin Franklin said it first. " },
{ "author":" Isaac Asimov " , "quoteText":" The two most common elements in the universe are hydrogen and stupidity. " },
{ "author":" Ludwig Erhard " , "quoteText":" Compromise is the art of dividing a cake so everyone believes he got the biggest piece. " },
{ "author":" Terri Weiner " , "quoteText":" It is the nature of emergencies to be inconvenient. " },
{ "author":" Stephen Fry " , "quoteText":" It\'s extremely unlucky to be superstitious, for no other reason than it is always unlucky to be colossally stupid. " },
{ "author":" Thomas Edison " , "quoteText":" Opportunity is missed by most people because it is dressed in overalls and looks like work. " },
{ "author":" Mark Twain " , "quoteText":" Don\'t go around saying the world owes you a living. The world owes you nothing; it was here first. " },
{ "author":" Marilyn Kennedy " , "quoteText":" It\'s better to be boldly decisive and risk being wrong than to agonize at length and be right too late. " },
{ "author":" George Patton " , "quoteText":" A good plan today is better than a perfect plan tomorrow.  " },
{ "author":" Winston Churchill " , "quoteText":" Man will occassionally stumble over the truth, but most of the time he will pick himself up and continue on. " },
{ "author":" Edward de Bono " , "quoteText":" It is better to have enough ideas for some of them to be wrong than to always be right by having no ideas at all. " },
{ "author":" Elbert Hubbard " , "quoteText":" The world is moving so fast these days that the man who says it can\'t be done is generally interrupted by someone doing it. " },
{ "author":" Unknown " , "quoteText":" It\'s a small world, but I wouldn\'t like to paint it. " },
{ "author":" Unknown " , "quoteText":" I don\'t suffer from insanity, I enjoy every minute of it. " },
{ "author":" Unknown " , "quoteText":" It\'s lonely at the top, but the food is better. " },
{ "author":" Unknown " , "quoteText":" Pride is what we have.  Vanity is what others have. " },
{ "author":" Unknown " , "quoteText":" Give me ambiguity or give me something else. " },
{ "author":" Unknown " , "quoteText":" Consciousness: that annoying time between naps. " },
{ "author":" Unknown " , "quoteText":" Why is abbreviation such a long word? " },
{ "author":" Unknown " , "quoteText":" We have enough youth, how about a fountain of Smart? " },
{ "author":" Unknown " , "quoteText":" Time is what keeps everything from happening all at once. " },
{ "author":" Popular Mechanics, 1949 " , "quoteText":" Computers in the future may weigh no more than 1.5 tons. " },
{ "author":" Thomas Watson " , "quoteText":" I think there is a world market for maybe five computers. " },
{ "author":" Unknown " , "quoteText":" If you don\'t find what you want in the Index, look very carefully through the entire catalogue. " },
{ "author":" Unknown " , "quoteText":" Computers make very fast, very accurate mistakes. " },
{ "author":" Unknown " , "quoteText":" Computers are not intelligent. They only think they are. " },
{ "author":" Unknown " , "quoteText":" Imagine if every thursday your shoes exploded if you tied them in the usual way. This happens to us all the time with computers, and nobody thinks of complaining! " },
{ "author":" Unknown " , "quoteText":" Tell a man there are 300 billion stars in the universe and he\'ll believe you. Tell him a seat has wet paint on it and he\'ll have to touch it to be sure. " },
{ "author":" Unknown " , "quoteText":" If you need anything please don\'t hesitate to ask someone else first. " },
{ "author":" Unknown " , "quoteText":" Some mornings, it\'s just not worth chewing through the leather straps. " },
{ "author":" Unknown " , "quoteText":" The statistics on sanity are that one out of every four people is suffering from some form of mental illness. Think of your three best friends. If they\'re okay, then it\'s you. " },
{ "author":" Unknown " , "quoteText":" If it weren\'t for electricity we\'d all be watching television by candlelight. " },
{ "author":" Unknown " , "quoteText":" You cannot have everything. I mean, where would you put it? " },
{ "author":" Woody Allen " , "quoteText":" I will not eat oysters. I want my food dead. Not sick, not wounded, dead. " },
{ "author":" Unknown " , "quoteText":" If toast always lands butter-side down, and cats always land on their feet, what happens if you drop a buttered cat? " },
{ "author":" Unknown " , "quoteText":" Nouvelle Cuisine, roughly translated, means: I can\'t believe I paid ninety-six pounds and I\'m still hungry. " },
{ "author":" Unknown " , "quoteText":" I went to a restaurant that serves \'breakfast at any time\'. So I ordered French Toast during the Renaissance. " },
{ "author":" Unknown " , "quoteText":" I went to a General Store, but they wouldn\'t sell me anything specific. " },
{ "author":" Unknown " , "quoteText":" A positive attitude will not solve all your problems, but it will annoy enough people to make it worth the effort. " },
{ "author":" Unknown " , "quoteText":" This year\'s Psychic Fair will be held on June 23rd. In the event of rain, it will be held the previous Saturday. " },
{ "author":" Unknown " , "quoteText":" \'Of course,\' said my grandfather, pulling a gun from his belt as he stepped from the Time Machine, \'There\'s no paradox if I shoot YOU\'. " },
{ "author":" Unknown " , "quoteText":" In theory, there is no difference between theory and practice. But, in practice, there is. " },
{ "author":" Salvador Dali " , "quoteText":" The only difference between me and a madman is that I\'m not mad. " },
{ "author":" Napoleon Bonaparte " , "quoteText":" Never interrupt your enemy when he is making a mistake. " },
{ "author":" Thomas Alva Edison " , "quoteText":" I have not failed. I\'ve just found 10,000 ways that won\'t work. " },
{ "author":" Voltaire " , "quoteText":" A witty saying proves nothing. " },
{ "author":" Unknown " , "quoteText":" Some drink at the fountain of knowledge...others just gargle. " },
{ "author":" Unknown " , "quoteText":" It\'s not an optical illusion, it just looks that way. " },
{ "author":" Unknown " , "quoteText":" When all else fails, read the instructions. " },
{ "author":" Unknown " , "quoteText":" Smile, it makes people wonder what you\'re thinking. " },
{ "author":" Unknown " , "quoteText":" Practice makes perfeckt. " },
{ "author":" Unknown " , "quoteText":" If you can remember the \'60s, then you weren\'t there. " },
{ "author":" Unknown " , "quoteText":" There is no surer way to ruin a good discussion than to contaminate it with facts. " },
{ "author":" Unknown " , "quoteText":" I can\'t make predictions and I never will " },
{ "author":" Unknown " , "quoteText":" The second best policy is dishonesty " },
{ "author":" Unknown " , "quoteText":" If it boils and is watched, it can\'t be a pot. " },
{ "author":" Unknown " , "quoteText":" I argue very well. Ask any of my remaining friends. I can win an argument on any topic, against any opponent. People know this, and steer clear of me at parties. " },
{ "author":" Unknown " , "quoteText":" If at first you don\'t succeed, then skydiving definitely isn\'t for you. " },
{ "author":" Unknown " , "quoteText":" If a vegetarian eats vegetables, what does a humanitarian eat? " },
{ "author":" Unknown " , "quoteText":" How can a slim chance and a fat chance be the same? " },
{ "author":" Mark Twain " , "quoteText":" For business reasons, I must maintain the outward signs of sanity. " },
{ "author":" Bertrand Russell " , "quoteText":" The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt. " },
{ "author":" Mark Twain " , "quoteText":" Only newspaper editors and people with tapeworms should ever refer to themselves as, \'we\'. " },
{ "author":" Mark Twain " , "quoteText":" It is better to remain silent and be thought a fool than to open one\'s mouth and remove all doubt. " },
{ "author":" Unknown " , "quoteText":" Never preceed anything more complex than a Frisbee throw with, \'Hey boss, watch this! " },
{ "author":" Oscar Wilde " , "quoteText":" It is best to mince one\'s words very finely, it makes them much easier to eat afterwards. " },
{ "author":" Winston Churchill " , "quoteText":" Never give up, never give up, never, never, never give up! " },
{ "author":" Ellsworth Toohey " , "quoteText":" Underneath the skin, all humanity are brothers and I would gladly skin humanity alive to prove it. " },
{ "author":" Shakespeare " , "quoteText":" There is nothing either good or bad, but thinking makes it so. " },
{ "author":" Stephen King " , "quoteText":" I guess when you turn off the main road, you have to be prepared to see some funny houses. " },
{ "author":" Unknown " , "quoteText":" Never let your sense of morals prevent you from doing what is right. " },
{ "author":" Unknown " , "quoteText":" When I was a kid my favorite relative was Uncle Caveman. After school we\'d all go play in his cave, and every once in a while he would eat one of us. It wasn\'t until later that I found out that Uncle Caveman was a bear. " },
{ "author":" Unknown " , "quoteText":" Take my advice: If the recipe calls for ‘3 handfuls of lava,’ it\'s really not worth the effort. " },
{ "author":" Groucho Marx. " , "quoteText":" Those are my principles. If you don\'t like them I have others. " },
{ "author":" Benjamin Franklin " , "quoteText":" Beer is proof that God loves us and wants us to be happy. " },
{ "author":" Unknown " , "quoteText":" There are 10 types of people in this world; those who understand the binary number system and those who do not. " },
{ "author":" Voltaire. " , "quoteText":" He was a great patriot, a humanitarian, a loyal friend; provided, of course, he really is dead. " },
{ "author":" Marion Barry " , "quoteText":" Outside of the killings, Washington has one of the lowest crime rates in the country. " },
{ "author":" Unknown " , "quoteText":" Every time I close the door on reality it comes in through the windows. " },
{ "author":" Unknown " , "quoteText":" Thirty-five is when you finally get your head together and your body starts falling apart. " },
{ "author":" Unknown " , "quoteText":" The tragedy of life doesn\'t lie in not reaching your goal. The tragedy lies in having no goal to reach. " },
{ "author":" Unknown " , "quoteText":" No great man ever complains of want of opportunity. " },
{ "author":" Dan Quayle " , "quoteText":" It isn\'t pollution that\'s harming the environment, it\'s the impurities in our air and water that are doing it. " },
{ "author":" Unknown " , "quoteText":" What if, at this very moment, you are living up to your full potential? " },
{ "author":" Unknown " , "quoteText":" Sanity calms, but madness is more interesting. " },
{ "author":" Unknown " , "quoteText":" Don\'t talk about yourself so much... we\'ll do that when you leave. " },
{ "author":" Unknown " , "quoteText":" If you try and don\'t succeed, cheat. Repeat until caught. Then lie. " },
{ "author":" Unknown " , "quoteText":" Never say ‘OOPS!’ always say ‘Ah, Interesting!’ " },
{ "author":" Unknown " , "quoteText":" This isn\'t burger king, you can\'t have it your way. " },
{ "author":" Unknown " , "quoteText":" If you must choose between two evils, pick the one you\'ve never tried before. " },
{ "author":" Charles H. Duell " , "quoteText":" Everything that can be invented has been invented. " },
{ "author":" Sir John Eric Ericksen " , "quoteText":" The abdomen, the chest, and the brain will forever be shut from the intrusion of the wise and humane surgeon.  " },
{ "author":" Pierre Pachet " , "quoteText":" Louis Pasteur\'s theory of germs is ridiculous fiction. " },
{ "author":" H.M. Warner " , "quoteText":" Who the hell wants to hear actors talk? " },
{ "author":" Decca Recording Co. rejecting the Beatles, 1962. " , "quoteText":" We don\'t like their sound, and guitar music is on the way out. " },
{ "author":" Lord Kelvin " , "quoteText":" Heavier-than-air flying machines are impossible. " },
{ "author":" Unknown " , "quoteText":" Two times a week, we go to a nice restaurant, a little wine, good food and companionship. She goes Mondays, I go Fridays.  " },
{ "author":" Unknown " , "quoteText":" Women will never be equal to men until they can walk down the street with a bald head and a beer gut, and still think they are beautiful. " }
 ]};

loadQuotes();